### ISSUE TITLE
Cross validation not working

### ISSUE THREAD

**Issue by leader80** [claeis/ilivalidator#27]
[2 - Schutzbauten_V05_zweite_Anhörung.ili.txt](https://github.com/claeis/ilivalidator/files/747434/2.-.Schutzbauten_V05_zweite_Anhorung.ili.txt)
[sb_test.xtf.txt](https://github.com/claeis/ilivalidator/files/747435/sb_test.xtf.txt)

Dear all,

how is it possible to crossvalidate the data?
The export from ili2pg and the ilivalidator is not validating our data, please have a look at the attached model and data.

Thanks
G.

**Comment by claeis** [comment]
fixed in 0.10.0

**Comment by giodegiorgi** [comment]
Could you please bring the same functionality in the ili2pg?

**Comment by edigonzales** [comment]
Since ilivalidator lib is used by ili2pg, I'm pretty sure it will be in the next ili2pg release "automagically".

**Comment by giodegiorgi** [comment]
cool, but I just tested the validator and I'm still having the same issues and on top now is not validating this:
```

 <Schutzbauten_LV03_V05.Schutzbauten BID="Schutzbauten_LV03_V05.Schutzbauten">
      <Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt TID="1321">
        <Datenherr>Kantone.AG</Datenherr>
        <Schutzbauten_ID>132100</Schutzbauten_ID>
        <Aggregierung>Einzelwerk</Aggregierung>
        <Hauptprozess>Wasser</Hauptprozess>
        <Werksart>Wasser.Schutz_vor_Ueberflutung_Uebersarung.Damm</Werksart>
        <Material>Erdmaterial</Material>
        <Laenge>123</Laenge>
        <Breite>12.0</Breite>
        <Hoehe>12.0</Hoehe>
        <Hoehe_zum_Umland>12.0</Hoehe_zum_Umland>
        <Flaeche>123</Flaeche>
        <Rueckhaltevolumen>123</Rueckhaltevolumen>
        <Anzahl>132</Anzahl>
        <Gesamtlaenge>12</Gesamtlaenge>
        <Gesamtflaeche>123</Gesamtflaeche>
        <Erstellungsjahr>2017</Erstellungsjahr>
        <Erhaltungsverantwortung_Kategorie>Kanton</Erhaltungsverantwortung_Kategorie>
        <Erhaltungsverantwortung_Name>test</Erhaltungsverantwortung_Name>
        <Zustand>gut_bis_annehmbar</Zustand>
      </Schutzbauten_LV03_V05.Schutzbauten.Schutzbautenobjekt>
    </Schutzbauten_LV03_V05.Schutzbauten>
```

please reopen the issue.
